FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm32v7 AS build-env
ARG BUILD_VERSION
ENV BUILD_VERSION=$BUILD_VERSION

WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out /p:Version=$BUILD_VERSION

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "RedisTimeSeriesEdge.dll"]