apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://$PROMETHEUS_HOST:9090

- name: Redis
  type: redis-datasource
  url: $REDIS_UNIX_SOCKET_DIR/redis.sock
  jsonData: 
    client: socket
  